### ISSUE TITLE
percy-playwright still broken after 1.0.1 push

### ISSUE THREAD

**Issue by unlikelyzero** [percy/percy-playwright#59]
## The problem

Unable to run percy-playwright

## Environment

https://app.circleci.com/pipelines/github/nasa/openmct/9655/workflows/82f71654-f5bc-4f65-882c-b8f787e746e9/jobs/30919

## Details
There is a broken transitive dependency somewhere

## Debug logs
```
openmct@2.0.2-SNAPSHOT test:e2e:ci
> npx playwright test --config=e2e/playwright-ci.config.js --project=chrome smoke default condition timeConductor


Running 6 tests using 2 workers


Error [ERR_REQUIRE_ESM]: require() of ES Module /root/project/node_modules/@percy/sdk-utils/dist/index.js from /root/project/node_modules/@percy/playwright/index.js not supported.
Instead change the require of /root/project/node_modules/@percy/sdk-utils/dist/index.js in /root/project/node_modules/@percy/playwright/index.js to a dynamic import() which is available in all CommonJS modules.

   at ../../node_modules/@percy/playwright/index.js:1

> 1 | const utils = require('@percy/sdk-utils');
    |               ^
  2 |
  3 | // Collect client and environment information
  4 | const sdkPkg = require('./package.json');

    at Object.<anonymous> (/root/project/node_modules/@percy/playwright/index.js:1:15)
    at Object.<anonymous> (/root/project/e2e/tests/visual/default.spec.js:36:23)
    at Loader._requireOrImport (/root/project/node_modules/@playwright/test/lib/loader.js:269:14)
    at Loader.loadTestFile (/root/project/node_modules/@playwright/test/lib/loader.js:139:18)
    at Runner._runFiles (/root/project/node_modules/@playwright/test/lib/runner.js:287:44)
    at async Runner._run (/root/project/node_modules/@playwright/test/lib/runner.js:223:12)
    at async TimeoutRunner.run (/root/project/node_modules/playwright-core/lib/utils/async.js:38:14)
    at async raceAgainstTimeout (/root/project/node_modules/playwright-core/lib/utils/async.js:85:15)
    at async Runner.runAllTests (/root/project/node_modules/@playwright/test/lib/runner.js:180:20)
    at async runTests (/root/project/node_modules/@playwright/test/lib/cli.js:175:18)
    at async Command.<anonymous> (/root/project/node_modules/@playwright/test/lib/cli.js:74:7)
::error ::Error [ERR_REQUIRE_ESM]: require() of ES Module /root/project/node_modules/@percy/sdk-utils/dist/index.js from /root/project/node_modules/@percy/playwright/index.js not supported.%0AInstead change the require of /root/project/node_modules/@percy/sdk-utils/dist/index.js in /root/project/node_modules/@percy/playwright/index.js to a dynamic import() which is available in all CommonJS modules.%0A%0A   at ../../node_modules/@percy/playwright/index.js:1%0A%0A> 1 | const utils = require('@percy/sdk-utils');%0A    |               ^%0A  2 |%0A  3 | // Collect client and environment information%0A  4 | const sdkPkg = require('./package.json');%0A%0A    at Object.<anonymous> (/root/project/node_modules/@percy/playwright/index.js:1:15)%0A    at Object.<anonymous> (/root/project/e2e/tests/visual/default.spec.js:36:23)%0A    at Loader._requireOrImport (/root/project/node_modules/@playwright/test/lib/loader.js:269:14)%0A    at Loader.loadTestFile (/root/project/node_modules/@playwright/test/lib/loader.js:139:18)%0A    at Runner._runFiles (/root/project/node_modules/@playwright/test/lib/runner.js:287:44)%0A    at async Runner._run (/root/project/node_modules/@playwright/test/lib/runner.js:223:12)%0A    at async TimeoutRunner.run (/root/project/node_modules/playwright-core/lib/utils/async.js:38:14)%0A    at async raceAgainstTimeout (/root/project/node_modules/playwright-core/lib/utils/async.js:85:15)%0A    at async Runner.runAllTests (/root/project/node_modules/@playwright/test/lib/runner.js:180:20)%0A    at async runTests (/root/project/node_modules/@playwright/test/lib/cli.js:175:18)%0A    at async Command.<anonymous> (/root/project/node_modules/@playwright/test/lib/cli.js:74:7)


  6 skipped
::notice title=🎭 Playwright Run Summary::  6 skipped

Exited with code exit status 1
```

## Code to reproduce issue

`npm install percy-playwright
npm run playwright-test`

**Comment by unlikelyzero** [comment]
@Robdel12 is this something that will occur today? I'll have to rip out our percy code to get the builds working again since we were already pinned to `percy/percy-playwright: 1.0.0-beta`

Also, I think that you all should consider https://github.com/percy/percy-playwright/issues/57 to this class of issue until you can get some CI tooling in place to cover transitive dependencies (no small lift). I think the general case of multi-package npm tooling is really only solved in `lerna`

**Comment by Robdel12** [comment]
This is something we want to release ASAP since all SDKs will be impacted by this

**Comment by unlikelyzero** [comment]
@Robdel12 we've disabled all percy checks for now. Is there an older version that we should pin to until the sdk fix is released?

**Comment by Robdel12** [comment]
This should be taken care of with 1.0.2: https://github.com/percy/percy-playwright/releases/tag/v1.0.2

**Comment by unlikelyzero** [comment]
@Robdel12 verified!
